// <auto-generated />
using System;
using Farmacontrol.Core.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Farmacontrol.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Farmacontrol.Core.Model.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("Farmacontrol.Core.Model.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Farmacontrol.Core.Model.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LotCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ManufacturingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierCode")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("Farmacontrol.Core.Model.InventoryMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("NewStock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreviousStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode");

                    b.ToTable("InventoryMovements");
                });

            modelBuilder.Entity("Farmacontrol.Core.Model.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiagnosisOrNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("DoctorLicense")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageOrFolioReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SaleCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SaleCode")
                        .IsUnique();

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("Farmacontrol.Core.Model.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SupplierCode");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("Farmacontrol.Core.Model.PurchaseDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LotCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseDetails");
                });

            modelBuilder.Entity("Farmacontrol.Core.Model.Sale", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("TEXT");

                    b.Property<string>("DoctorLicense")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVoided")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Farmacontrol.Core.Model.SaleDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SaleCode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SaleCode1")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SaleCode");

                    b.HasIndex("SaleCode1");

                    b.ToTable("SaleDetails");
                });

            modelBuilder.Entity("Farmacontrol.Core.Model.Supplier", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxId")
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.HasIndex("Name");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Farmacontrol.Core.Model.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Farmacontrol.Model.Product", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Laboratory")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subcategory")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Product");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProductSupplier", b =>
                {
                    b.Property<string>("ProductsCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuppliersCode")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductsCode", "SuppliersCode");

                    b.HasIndex("SuppliersCode");

                    b.ToTable("ProductSupplier");
                });

            modelBuilder.Entity("Farmacontrol.Core.Model.UserEntity.Administrator", b =>
                {
                    b.HasBaseType("Farmacontrol.Core.Model.User");

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("Farmacontrol.Core.Model.UserEntity.Employee", b =>
                {
                    b.HasBaseType("Farmacontrol.Core.Model.User");

                    b.HasDiscriminator().HasValue("Empleado");
                });

            modelBuilder.Entity("Farmacontrol.Core.Model.ProductEntity.Cosmetic", b =>
                {
                    b.HasBaseType("Farmacontrol.Model.Product");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Hypoallergenic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Presentation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Products", t =>
                        {
                            t.Property("Brand")
                                .HasColumnName("Cosmetic_Brand");

                            t.Property("Presentation")
                                .HasColumnName("Cosmetic_Presentation");

                            t.Property("Type")
                                .HasColumnName("Cosmetic_Type");
                        });

                    b.HasDiscriminator().HasValue("Cosmetico");
                });

            modelBuilder.Entity("Farmacontrol.Core.Model.ProductEntity.Medicine", b =>
                {
                    b.HasBaseType("Farmacontrol.Model.Product");

                    b.Property<string>("ActivePrinciple")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Concentration")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsControlled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Presentation")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresPrescription")
                        .HasColumnType("INTEGER");

                    b.ToTable("Products", t =>
                        {
                            t.Property("ActivePrinciple")
                                .HasColumnName("Medicine_ActivePrinciple");

                            t.Property("Concentration")
                                .HasColumnName("Medicine_Concentration");
                        });

                    b.HasDiscriminator().HasValue("Medicamento");
                });

            modelBuilder.Entity("Farmacontrol.Core.Model.ProductEntity.Supplement", b =>
                {
                    b.HasBaseType("Farmacontrol.Model.Product");

                    b.Property<string>("ActivePrinciple")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Concentration")
                        .HasColumnType("TEXT");

                    b.Property<int>("Format")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecommendedDosage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Products", t =>
                        {
                            t.Property("Type")
                                .HasColumnName("Supplement_Type");
                        });

                    b.HasDiscriminator().HasValue("Suplemento");
                });

            modelBuilder.Entity("Farmacontrol.Core.Model.ProductEntity.Supply", b =>
                {
                    b.HasBaseType("Farmacontrol.Model.Product");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSterile")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Suministro");
                });

            modelBuilder.Entity("Farmacontrol.Core.Model.Batch", b =>
                {
                    b.HasOne("Farmacontrol.Model.Product", "Product")
                        .WithMany("Batches")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Farmacontrol.Core.Model.InventoryMovement", b =>
                {
                    b.HasOne("Farmacontrol.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Farmacontrol.Core.Model.Prescription", b =>
                {
                    b.HasOne("Farmacontrol.Core.Model.Sale", "Sale")
                        .WithOne("Prescription")
                        .HasForeignKey("Farmacontrol.Core.Model.Prescription", "SaleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Farmacontrol.Core.Model.Purchase", b =>
                {
                    b.HasOne("Farmacontrol.Core.Model.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Farmacontrol.Core.Model.PurchaseDetail", b =>
                {
                    b.HasOne("Farmacontrol.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Farmacontrol.Core.Model.Purchase", "Purchase")
                        .WithMany("Details")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Farmacontrol.Core.Model.SaleDetail", b =>
                {
                    b.HasOne("Farmacontrol.Core.Model.Sale", null)
                        .WithMany("Details")
                        .HasForeignKey("SaleCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Farmacontrol.Core.Model.Sale", null)
                        .WithMany("GetDetails")
                        .HasForeignKey("SaleCode1");
                });

            modelBuilder.Entity("ProductSupplier", b =>
                {
                    b.HasOne("Farmacontrol.Model.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Farmacontrol.Core.Model.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SuppliersCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Farmacontrol.Core.Model.Purchase", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Farmacontrol.Core.Model.Sale", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("GetDetails");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Farmacontrol.Model.Product", b =>
                {
                    b.Navigation("Batches");
                });
#pragma warning restore 612, 618
        }
    }
}
